### ISSUE TITLE
Create Collector API persistence with Google Cloud Datastore

### ISSUE THREAD

**Issue by robskrob** [chadwpry/prototype-content-consumer#5]
Description: The API needs to have an endpoint for persisting selector data.

Expectations:
1. Clients can request dynamic responses from server for Selector data on a page
2. Clients can POST to a specific endpoint with data from any HTML page to persist collector data.

Implementation:
1. Install gcloud and its corresponding platform service Google Cloud Datastore.
2. Activate and configure application to use the above document storage solution.
3. Define endpoint for the POST route to save the selector data into Google Cloud Datastore.
4. Define endpoint for a request to GET selector data by hostname
5. Define draw route and define endpoint for POST collector data

**Comment by chadwpry** [comment]
This has been implemented.
